services:
  db:
    image: maria_image:tag
    pull_policy: never
    container_name: mariadb-db
    restart: always
    environment:
      MYSQL_DATABASE: emprendedores_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  django:
    image: django_image:tag
    pull_policy: never
    container_name: django-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: emprendedores_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
      MYSQL_HOST: db
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
    volumes:
      - ./backend/django_backend:/app

  fastapi:
    image: fastapi_image:tag
    pull_policy: never
    container_name: fastapi-gateway
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - ./backend/api_gateway:/app

  react:
    image: react_image:tag
    pull_policy: never
    container_name: react-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://django:8000
    volumes:
      - ./frontend/react_app:/app

volumes:
  db_data:
