services:
  db:
    image: mariadb:10.11
    container_name: mariadb-db
    restart: always
    environment:
      MYSQL_DATABASE: emprendedores_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:  
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: emprendedores_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
      MYSQL_HOST: db
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
    command: >
      sh -c "/app/wait-for-it.sh db:3306 -- python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "9000:9000"
    depends_on:
      - db

  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"

volumes:
  db_data:
