version: "3.8"

services:
  django:
    image: django:tag
    container_name: django-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env  # Monta el archivo .env dentro del contenedor

  fastapi:
    image: fastapi:tag
    container_name: fastapi-gateway
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      - FRONTEND_URL=${FRONTEND_URL}

  react:
    image: react:tag
    container_name: react-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
