# Generated by Django 4.2 on 2025-04-27 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('ID_negocio', models.BigAutoField(primary_key=True, serialize=False)),
                ('ID_costo', models.BigIntegerField(blank=True, null=True)),
                ('ID_inversion', models.BigIntegerField(blank=True, null=True)),
                ('Nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('ID_usuario', models.ForeignKey(blank=True, db_column='ID_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'negocio',
            },
        ),
    ]
