# Generated by Django 4.2 on 2025-04-27 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='ID_usuario',
            field=models.ForeignKey(blank=True, db_column='ID_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='negocio',
            table=None,
        ),
    ]
