# Generated by Django 4.2 on 2025-04-27 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('negocio', '0002_alter_negocio_id_usuario_alter_negocio_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='ID_usuario',
            field=models.ForeignKey(blank=True, db_column='ID_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios', to=settings.AUTH_USER_MODEL),
        ),
    ]
